### ISSUE TITLE
third_party/ paths in non-generated bindings

### ISSUE THREAD

**Issue by muth02446** [google/dart-gl#10]
The part of the bindings which are not generated have links to third_party/

I had to manually adjust the paths to make things compile

**Comment by jtmcdole** [comment]
Ah, that should not have happened, all third_party links should have been cleaned up before.

**Comment by lyceel** [comment]
Doh!  That was my mistake after fixing issue #8.  Thanks for the heads-up.

**Comment by jtmcdole** [comment]
a4433eddeaa76a7560a9110e5aa099dcdbcb609e
