### ISSUE TITLE
build instructions are stale

### ISSUE THREAD

**Issue by muth02446** [google/dart-gl#11]

**Comment by muth02446** [comment]
on ubuntu 16.04:

-std=c++11 seems to be required  as a g++ argument.

I needed to set the following env vars
DART_SDK=/usr/lib/dart
GL_INCLUDE=/usr/include/GLES2/

**Comment by jtmcdole** [comment]
I've added -std=c++11 to the compile recipe.

a4433eddeaa76a7560a9110e5aa099dcdbcb609e
