### ISSUE TITLE
How about Windows support?

### ISSUE THREAD

**Issue by orklann** [google/dart-gl#18]
Can this library works on Windows?

**Comment by jtmcdole** [comment]
Yes. I develop on windows at home and try to make sure this stays operational.

**Comment by jtmcdole** [comment]
Note; windows has some funny dll shuffling... you have to a) have some gles2.0 library (mali has one such abstraction) b) have all the dll's in the right path.  I've had this working with the Nvidia drivers before as well, I just need to dig up the instructions.

With the dll open that we're doing now, we should / could distribute the DLLs with the package so there wouldn't be a need to build it locally.  Right now we've left that as 'an exercise for the developer'.
