### ISSUE TITLE
glShaderBinary_native causes compile errors

### ISSUE THREAD

**Issue by muth02446** [google/dart-gl#9]
This is for ubuntu 16.04

had to comment out this line to make things work
//{"glShaderBinary", glShaderBinary_native},

**Comment by lyceel** [comment]
glShaderBinary is a valid entry point in the OpenGL ES 2.0 API.  What issue are you having with it?

**Comment by jtmcdole** [comment]
Commented out now. I'm not sure why we don't have this in manual bindings...

a4433eddeaa76a7560a9110e5aa099dcdbcb609e
